[/Script/HardwareTargeting.HardwareTargetingSettings]
; quality settings
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/Engine.RendererSettings]
; exposure control and tone mapping settings
r.Tonemapper.Sharpen=2
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True
r.DefaultFeature.Bloom=False
r.DefaultFeature.AutoExposure=False
r.DefaultFeature.LocalExposure.HighlightContrastScale=0.8
r.DefaultFeature.LocalExposure.HighlightContrastScale=1.0
r.DefaultFeature.LocalExposure.ShadowContrastScale=0.8
r.DefaultFeature.LocalExposure.ShadowContrastScale=1.0
r.DefaultFeature.MotionBlur=False
r.SceneRenderTargetResizeMethod=2


;dynamic gi settings
r.LightPropagationVolume=0

; quality settings
r.ReflectionCaptureResolution=2048
r.AllowStaticLighting=True
r.HighResScreenshotDelay=8
r.DefaultBackBufferPixelFormat=4
r.AllowGlobalClipPlane=False
r.GBufferFormat=3

; shader settings
r.PostProcessing.PropagateAlpha=1
r.SupportSkyAtmosphereAffectsHeightFog=True
r.DefaultFeature.LensFlare=False
r.ClearCoatNormal=False
r.NormalMapsForStaticLighting=False



r.GenerateMeshDistanceFields=True

r.DynamicGlobalIlluminationMethod=1

r.ReflectionMethod=1

r.SkinCache.CompileShaders=True

r.RayTracing=True

r.Shadow.Virtual.Enable=1
r.VirtualTextures=True
r.Lumen.Reflections.HardwareRayTracing.Translucent.Refraction.EnableForProject=True
r.Lumen.HardwareRayTracing=True
r.Lumen.TranslucencyReflections.FrontLayer.EnableForProject=False
r.RayTracing.Shadows=True
r.MegaLights.EnableForProject=False
r.AllowOcclusionQueries=False
r.VirtualTexturedLightmaps=False
r.TextureStreaming=False
bEnableVirtualTextureOpacityMask=True

[/Script/EngineSettings.GameMapsSettings]
;defines what level to be loaded by default in the editor and at playback time
GameDefaultMap=/Game/VProdProject/Maps/Ndisplay.Ndisplay
EditorStartupMap=/Game/Maps/Default.Default

[/Script/UnrealEd.UnrealEdEngine]
; Remove Engine Template maps
-TemplateMapInfos=(ThumbnailTexture=Texture2D'/Engine/Maps/Templates/Thumbnails/VR-Basic.VR-Basic',Map="/Engine/Maps/Templates/VR-Basic")


;Allows for Hardware Accelerated Video Decoding

[/Script/WmfMediaFactory.WmfMediaSettings]
AllowNonStandardCodecs=True
HardwareAcceleratedVideoDecoding=True
LowLatency=False
NativeAudioOut=False

;Adds Virtual Scouting Widget for VR Scouting

[/Script/VPUtilitiesEditor.VPUtilitiesEditorSettings]
VirtualScoutingUI=/VirtualProductionUtilities/Editor/VirtualScoutingWidget.VirtualScoutingWidget_C

; Enables WebControl API
WebControl.EnableServerOnStartup=1

;Adds Remote Session for Vcam

[RemoteSession]
+Channels=(Name=FRemoteSessionFrameBufferChannel,Mode=Write)
+Channels=(Name=FRemoteSessionInputChannel,Mode=Read)
+Channels=(Name=FRemoteSessionXRTrackingChannel,Mode=Read)

;Setup for Media Profiles

[/Script/MediaFrameworkUtilities.MediaProfileSettings]
bApplyInCommandlet=False
MediaSourceProxy=/Game/VprodProject/MediaIO/MediaSource-01.MediaSource-01
MediaSourceProxy=/Game/VprodProject/MediaIO/MediaSource-02.MediaSource-02
MediaOutputProxy=/Game/VprodProject/MediaIO/MediaOutput-01.MediaOutput-01
StartupMediaProfile=None


;Setup for Multiuser

[/Script/Concert.ConcertClientConfig]
bIsHeadless=False
bInstallEditorToolbarButton=True
bAutoConnect=False
DefaultServerURL=
DefaultSessionName=
DefaultSessionToRestore=
DefaultSaveSessionAs=
ClientSettings=(DisplayName="",AvatarColor=(R=1.000000,G=1.000000,B=1.000000,A=1.000000),DesktopAvatarActorClass=/ConcertSyncClient/DesktopPresence.DesktopPresence_C,VRAvatarActorClass=/ConcertSyncClient/VRPresence.VRPresence_C,DiscoveryTimeoutSeconds=5,SessionTickFrequencySeconds=1,LatencyCompensationMs=0.000000,Tags=)
EndpointSettings=(bEnableLogging=False,PurgeProcessedMessageDelaySeconds=30,RemoteEndpointTimeoutSeconds=60)


;Setup for Ndisplay Cluster

[/Script/DisplayClusterEditor.DisplayClusterEditorSettings]
bEnabled=True

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
-D3D12TargetedShaderFormats=PCD3D_SM5
+D3D12TargetedShaderFormats=PCD3D_SM6
-D3D11TargetedShaderFormats=PCD3D_SM5
+D3D11TargetedShaderFormats=PCD3D_SM5

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_ME_VprodBP",NewGameName="/Script/MyProject2")
+ActiveGameNameRedirects=(OldGameName="/Script/TP_ME_VprodBP",NewGameName="/Script/MyProject2")
NearClipPlane=0.100000
bAllowMultiThreadedAnimationUpdate=True

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=3A3DBD464F3C9E8462AA0C9D5218F3B6
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

[/Script/Engine.AnimationSettings]
CompressCommandletVersion=2
+KeyEndEffectorsMatchNameArray=IK
+KeyEndEffectorsMatchNameArray=eye
+KeyEndEffectorsMatchNameArray=weapon
+KeyEndEffectorsMatchNameArray=hand
+KeyEndEffectorsMatchNameArray=attach
+KeyEndEffectorsMatchNameArray=camera
ForceRecompression=False
bForceBelowThreshold=False
bFirstRecompressUsingCurrentOrDefault=True
bRaiseMaxErrorToExisting=False
bEnablePerformanceLog=False
bStripAnimationDataOnDedicatedServer=False
bTickAnimationOnSkeletalMeshInit=True
BoneTimecodeCustomAttributeNameSettings=(HourAttributeName="TCHour",MinuteAttributeName="TCMinute",SecondAttributeName="TCSecond",FrameAttributeName="TCFrame",SubframeAttributeName="TCSubframe",RateAttributeName="TCRate",TakenameAttributeName="Takename")
+BoneCustomAttributesNames=(Name="test",Meaning="camera anim")
AttributeBlendModes=()
DefaultAttributeBlendMode=Blend
+MirrorFindReplaceExpressions=(FindExpression="r_",ReplaceExpression="l_",FindReplaceMethod=Prefix)
+MirrorFindReplaceExpressions=(FindExpression="l_",ReplaceExpression="r_",FindReplaceMethod=Prefix)
+MirrorFindReplaceExpressions=(FindExpression="R_",ReplaceExpression="L_",FindReplaceMethod=Prefix)
+MirrorFindReplaceExpressions=(FindExpression="L_",ReplaceExpression="R_",FindReplaceMethod=Prefix)
+MirrorFindReplaceExpressions=(FindExpression="_l",ReplaceExpression="_r",FindReplaceMethod=Suffix)
+MirrorFindReplaceExpressions=(FindExpression="_r",ReplaceExpression="_l",FindReplaceMethod=Suffix)
+MirrorFindReplaceExpressions=(FindExpression="_R",ReplaceExpression="_L",FindReplaceMethod=Suffix)
+MirrorFindReplaceExpressions=(FindExpression="_L",ReplaceExpression="_R",FindReplaceMethod=Suffix)
+MirrorFindReplaceExpressions=(FindExpression="right",ReplaceExpression="left",FindReplaceMethod=Prefix)
+MirrorFindReplaceExpressions=(FindExpression="left",ReplaceExpression="right",FindReplaceMethod=Prefix)
+MirrorFindReplaceExpressions=(FindExpression="Right",ReplaceExpression="Left",FindReplaceMethod=Prefix)
+MirrorFindReplaceExpressions=(FindExpression="Left",ReplaceExpression="Right",FindReplaceMethod=Prefix)
+MirrorFindReplaceExpressions=(FindExpression="([^}]*)_l_([^}]*)",ReplaceExpression="$1_r_$2",FindReplaceMethod=RegularExpression)
+MirrorFindReplaceExpressions=(FindExpression="([^}]*)_r_([^}]*)",ReplaceExpression="$1_l_$2",FindReplaceMethod=RegularExpression)
+MirrorFindReplaceExpressions=(FindExpression="([^}]*)_L_([^}]*)",ReplaceExpression="$1_R_$2",FindReplaceMethod=RegularExpression)
+MirrorFindReplaceExpressions=(FindExpression="([^}]*)_R_([^}]*)",ReplaceExpression="$1_L_$2",FindReplaceMethod=RegularExpression)
+MirrorFindReplaceExpressions=(FindExpression="([^}]*)_left_([^}]*)",ReplaceExpression="$1_right_$2",FindReplaceMethod=RegularExpression)
+MirrorFindReplaceExpressions=(FindExpression="([^}]*)_right_([^}]*)",ReplaceExpression="$1_left_$2",FindReplaceMethod=RegularExpression)
+MirrorFindReplaceExpressions=(FindExpression="([^}]*)_Left_([^}]*)",ReplaceExpression="$1_Right_$2",FindReplaceMethod=RegularExpression)
+MirrorFindReplaceExpressions=(FindExpression="([^}]*)_Right_([^}]*)",ReplaceExpression="$1_Left_$2",FindReplaceMethod=RegularExpression)
+MirrorFindReplaceExpressions=(FindExpression="((?:^[sS]pine|^[rR]oot|^[pP]elvis|^[nN]eck|^[hH]ead|^ik_hand_gun).*)",ReplaceExpression="$1",FindReplaceMethod=RegularExpression)
DefaultFrameRate=(Numerator=25,Denominator=1)
bEnforceSupportedFrameRates=False

[/Script/Engine.VirtualTexturePoolConfig]
DefaultSizeInMegabyte=10000
bPoolAutoGrowInEditor=False
+Pools=(Formats=(PF_DXT1),MinTileSize=136,MaxTileSize=136,SizeInMegabyte=2048,bEnableResidencyMipMapBias=False,bAllowSizeScale=False,MinScaledSizeInMegabyte=0,MaxScaledSizeInMegabyte=0)
+Pools=(Formats=(PF_BC5),MinTileSize=136,MaxTileSize=136,SizeInMegabyte=2048,bEnableResidencyMipMapBias=False,bAllowSizeScale=False,MinScaledSizeInMegabyte=0,MaxScaledSizeInMegabyte=0)
+Pools=(Formats=(PF_DXT5),MinTileSize=136,MaxTileSize=136,SizeInMegabyte=2048,bEnableResidencyMipMapBias=False,bAllowSizeScale=False,MinScaledSizeInMegabyte=0,MaxScaledSizeInMegabyte=0)


[/Script/LevelSequence.LevelSequenceProjectSettings]
LevelSequence.DefaultDisplayRate=25fps

[/Script/MovieRenderPipelineCore.MoviePipelineCommandLineEncoderSettings]
ExecutablePath=ffmpeg
VideoCodec=libx264
AudioCodec=aac
OutputFileExtension=mp4

